title: "JOURNÉES FRANCOPHONES <br>de PROGRAMMATION par CONTRAINTES"
shorttitle: "JFPC 2021"
date: "Du 22 au 24 juin 2021"
oldlocation: "NICE <br>CAMPUS TROTABAS"
location: "EN LIGNE"
description: "JFPC du 22 au 24 juin 2021 à Nice"
baseurl: "/jfpc_2021" # the subpath of your site, e.g. /blog
url: "https://www.i3s.unice.fr"

facebook:
  app_id: 

logo: "⁨assets⁩/img/favicon.png"

language: 'fr'

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github fa-lg
    url: https://github.com/mpelleau/jfpc2021
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: /:categories/:title/

sass:
  sass_dir: _sass
  style: :expanded
  line_numbers: true
  sourcemap: always

exclude:
    - Gemfile
    - Gemfile.lock
    - README.md
    - INSTALL.md
